name: In-Mem Leak MacOS

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  in-memory-leak-tests-macos:
    name: In-Memory Leak Tests MacOS
    runs-on: macos-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.24'

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22'

    - name: Run in-memory leak tests
      run: |
        make node_inmem_memory

