name: Tests

on:
  push:
    branches: [ devtest ]
  pull_request:
    branches: [ devtest ]

jobs:
  in-memory-and-swarm-integration-tests:
    name: In-Memory and Swarm Integration Tests Ubuntu
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.24'

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22'

    - name: Set zsh
      run: |
        apt-get -y install zsh

    - name: Run simulation and in-memory tests
      run: |
        make node_sim_test
        make node_inmem_test

    - name: Install fdp-play
      run: |
        npm install -g @fairdatasociety/fdp-play
        fdp-play --version

    - name: Install swarm-cli
      run: |
        npm install --global @ethersphere/swarm-cli
        swarm-cli --version

    - name: Start fdp-play environment
      run: |
        fdp-play start --detach

    - name: Buy postage batch
      run: |
        BATCH_ID=$(swarm-cli stamp buy --depth 20 --amount 1b --quiet)
        echo "BEE_BATCH_ID=$BATCH_ID" >> $GITHUB_ENV
        echo "Postage Batch ID: $BATCH_ID"

    - name: Run swarm integration tests
      run: |
        make node_locnet_test

    - name: Stop fdp-play environment
      if: always()
      run: |
        fdp-play stop

